import Head from 'next/head'
import { Inter } from 'next/font/google'
import Banner from '../../components/banner/banner'
import Navbar from '../../components/nav/navbar'
import SectionCards from '../../components/card/section-cards'

import { getVideos } from '../../lib/videos'

import styles from '../styles/Home.module.css'
import { ICardSectionVideos } from '../../types'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const disneyVideos = await getVideos()
  console.log(disneyVideos);
  return { props: { disneyVideos } }
}

interface IHomeProps {
  disneyVideos: ICardSectionVideos[]
}

export default function Home({ disneyVideos }: IHomeProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar userName="benyamin@ben.com" />
      <Banner
        imgUrl="/static/clifford.webp"
        subTitle="very cute dog"
        title="clifford the big dog"
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
      </div>
    </>
  )
}
